package com.iplauction.jcrud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.iplauction.jcrud.utils.LeagueUserListTypeConverter;
import org.springframework.data.annotation.Id;

import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "league_info")
public class LeagueInfo {

    private String leagueId;
    private String leagueName;
    private List<LeagueUser> leagueUsers;
    private Date createdDateTime;
    private Date lastModifiedDateTime;
    private Boolean isActive = true;
    private String leagueStatus;

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getLeagueId() {
        return leagueId;
    }

    public void setLeagueId(String leagueId) {
        this.leagueId = leagueId;
    }

    @DynamoDBAttribute
    public String getLeagueName() {
        return leagueName;
    }

    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName;
    }


    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public Date getCreatedDateTime() {
        return createdDateTime;
    }

    public void setCreatedDateTime(Date createdDateTime) {
        this.createdDateTime = createdDateTime;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getLastModifiedDateTime() {
        return lastModifiedDateTime;
    }

    public void setLastModifiedDateTime(Date lastModifiedDateTime) {
        this.lastModifiedDateTime = lastModifiedDateTime;
    }

    public Boolean getIsActive() {
        return isActive;
    }
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    @DynamoDBTypeConverted(converter = LeagueUserListTypeConverter.class)
    public List<LeagueUser> getLeagueUsers() {
        return leagueUsers;
    }

    public void setLeagueUsers(List<LeagueUser> leagueUsers) {
        this.leagueUsers = leagueUsers;
    }

    @DynamoDBAttribute
    public String getLeagueStatus() {
        return leagueStatus;
    }

    public void setLeagueStatus(String leagueStatus) {
        this.leagueStatus = leagueStatus;
    }
}
